name: "Teams Notification"
description: "Send a modernized Adaptive Card notification to Microsoft Teams via Webhook."

inputs:
  webhook_url:
    description: "The Microsoft Teams Incoming Webhook URL."
    required: true
  message:
    description: "The main body text of the notification."
    required: true
  title:
    description: "The title of the notification card."
    required: false
    default: "Deployment Notification"
  status:
    description: "The status of the event (success, failure, info). Determines color and emoji."
    required: false
    default: "info"
  environment:
    description: "The name of the environment (e.g., Production, Staging)."
    required: false
    default: "Production"
  deployment_url:
    description: "URL to the deployed application."
    required: false
  run_id:
    description: "GitHub Run ID to link back to the workflow logs."
    required: false
  version:
    description: "Version of the application being deployed."
    required: false
  branch:
    description: "The branch name."
    required: false
  author:
    description: "The author of the commit/deployment."
    required: false

runs:
  using: "node20"
  main: "index.js"
