name: "Teams Notification"
description: "Send a notification to Microsoft Teams with deployment information using a file-based JSON template."

inputs:
  logic_app_url:
    description: "URL of the Logic App HTTP trigger endpoint"
    required: true
  template_path:
    description: "Path to the JSON template file relative to the repository root"
    required: false
    default: ".github/actions/teams-notification/logic-app-template.json"
  webhook_url:
    description: "Microsoft Teams webhook URL"
    required: true
  message:
    description: "Notification message"
    required: true
  environment:
    description: "Deployment environment (e.g. staging, prod)"
    required: true
  deployment_url:
    description: "URL of the deployed site"
    required: true
  branch:
    description: "Branch that was deployed"
    required: true
  location_code:
    description: "Location code of the deployment"
    required: true
  resource_group:
    description: "Resource group name"
    required: true
  approval_url:
    description: "URL for approval action (staging only)"
    required: false
    default: ""
  rollback_url:
    description: "URL for rollback action (prod only)"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Checkout Repository for Template
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Read and Substitute Template
      shell: bash
      id: build_payload
      run: |
        TEMPLATE=$(cat "$(pwd)/${{ inputs.template_path }}")
        PAYLOAD=$(echo "$TEMPLATE" | sed -e "s|{{teamsWebhookUrl}}|${{ inputs.webhook_url }}|g" -e "s|{{locationCode}}|${{ inputs.location_code }}|g" -e "s|{{resourceGroup}}|${{ inputs.resource_group }}|g" -e "s|{{environment}}|${{ inputs.environment }}|g" -e "s|{{branch}}|${{ inputs.branch }}|g" -e "s|{{message}}|${{ inputs.message }}|g" -e "s|{{deploymentUrl}}|${{ inputs.deployment_url }}|g" -e "s|{{approvalUrl}}|${{ inputs.approval_url }}|g" -e "s|{{rollbackUrl}}|${{ inputs.rollback_url }}|g")
        echo "Generated Payload:"
        echo "$PAYLOAD"
        echo "payload=$PAYLOAD" >> $GITHUB_OUTPUT

    - name: Debug: Show Logic App URL and Payload
      shell: bash
      run: |
        echo "Logic App URL: ${{ inputs.logic_app_url }}"
        echo "Payload to be sent:"
        echo "${{ steps.build_payload.outputs.payload }}" | jq .

    - name: Invoke Logic App HTTP Trigger
      shell: bash
      run: |
        echo "Invoking Logic App via HTTP trigger..."
        RESPONSE=$(curl -s -w "\nHTTP_STATUS:%{http_code}" -X POST \
          -H "Content-Type: application/json" \
          -d "$(echo "${{ steps.build_payload.outputs.payload }}" | jq -c .)" \
          "${{ inputs.logic_app_url }}")
        echo "Response from Logic App:"
        echo "$RESPONSE"
