name: "Teams Notification"
description: "Send a notification to Microsoft Teams with deployment information using a file-based JSON template, encoding GitHub and Teams tokens."

inputs:
  logic_app_url:
    description: "URL of the Logic App HTTP trigger endpoint"
    required: true
  template_path:
    description: "Path to the JSON template file relative to the repository root"
    required: false
    default: ".github/actions/teams-notification/logic-app-teams-template.json"
  webhook_url:
    description: "Microsoft Teams webhook URL"
    required: false
    default: "https://phoenixvc568.webhook.office.com/webhookb2/..."
  message:
    description: "Notification message"
    required: true
  environment:
    description: "Deployment environment (e.g. staging, prod)"
    required: true
  deployment_url:
    description: "URL of the deployed site"
    required: true
  branch:
    description: "Branch that was deployed"
    required: true
  location_code:
    description: "Location code of the deployment"
    required: true
  resource_group:
    description: "Resource group name"
    required: true
  approval_url:
    description: "URL for approval action (staging only)"
    required: false
    default: ""
  rollback_url:
    description: "URL for rollback action (prod only)"
    required: false
    default: ""
  github_token:
    description: "GitHub token to be encoded and passed along"
    required: true
  teams_token:
    description: "Teams token to be encoded and passed along"
    required: true
  teams_logic_app_url:
    description: "Teams Logic App URL"
    required: true
  github_logic_app_url:
    description: "GitHub Logic App URL"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout Repository for Template
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Read and Substitute Template
      shell: bash
      id: build_payload
      run: |
        # Encode tokens in base64
        encodedGitHubToken=$(echo "${{ inputs.github_token }}" | base64)
        encodedTeamsToken=$(echo "${{ inputs.teams_token }}" | base64)
        echo "Encoded GitHub token: $encodedGitHubToken"
        echo "Encoded Teams token: $encodedTeamsToken"

        # Read the JSON template file
        TEMPLATE=$(cat "$(pwd)/${{ inputs.template_path }}")
        echo "Template contents:"
        echo "$TEMPLATE"

        # Substitute placeholders in the template
        PAYLOAD=$(echo "$TEMPLATE" | sed \
          -e "s|{{teamsWebhookUrl}}|${{ inputs.webhook_url }}|g" \
          -e "s|{{locationCode}}|${{ inputs.location_code }}|g" \
          -e "s|{{resourceGroup}}|${{ inputs.resource_group }}|g" \
          -e "s|{{environment}}|${{ inputs.environment }}|g" \
          -e "s|{{branch}}|${{ inputs.branch }}|g" \
          -e "s|{{message}}|${{ inputs.message }}|g" \
          -e "s|{{deploymentUrl}}|${{ inputs.deployment_url }}|g" \
          -e "s|{{approvalUrl}}|${{ inputs.approval_url }}|g" \
          -e "s|{{rollbackUrl}}|${{ inputs.rollback_url }}|g" \
          -e "s|{{encodedToken}}|$encodedGitHubToken|g" \
          -e "s|{{encodedTeamsToken}}|$encodedTeamsToken|g" \
          -e "s|{{teamsLogicAppUrl}}|${{ inputs.teams_logic_app_url }}|g" \
          -e "s|{{githubLogicAppUrl}}|${{ inputs.github_logic_app_url }}|g")
        echo "Generated Payload:"
        echo "$PAYLOAD"

        # Write the payload as a multi-line output
        echo "payload<<EOF" >> $GITHUB_OUTPUT
        echo "$PAYLOAD" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Invoke Logic App HTTP Trigger
      shell: bash
      run: |
        echo "Invoking Logic App via HTTP trigger..."

        # Use jq to parse and compact JSON safely
        COMPACT_PAYLOAD=$(jq -c . <<< '${{ steps.build_payload.outputs.payload }}')

        echo "Payload to be sent:"
        echo "$COMPACT_PAYLOAD"

        RESPONSE=$(curl -s -w "\nHTTP_STATUS:%{http_code}" -X POST -H "Content-Type: application/json" \
          -d "$COMPACT_PAYLOAD" \
          "${{ inputs.logic_app_url }}")

        echo "Response from Logic App:"
        echo "$RESPONSE"
