name: "Teams Notification"
description: "Send a notification to Microsoft Teams with deployment information using a file-based JSON template, encoding GitHub and Teams tokens."

inputs:
  logic_app_url:
    description: "URL of the Logic App HTTP trigger endpoint"
    required: true
  template_path:
    description: "Path to the JSON template file relative to the repository root"
    required: false
    default: ".github/actions/teams-notification/logic-app-teams-template.json"
  webhook_url:
    description: "Microsoft Teams webhook URL"
    required: false
    default: "https://phoenixvc568.webhook.office.com/webhookb2/..."
  message:
    description: "Notification message"
    required: true
  environment:
    description: "Deployment environment (e.g. staging, prod)"
    required: true
  deployment_url:
    description: "URL of the deployed site"
    required: true
  branch:
    description: "Branch that was deployed"
    required: true
  location_code:
    description: "Location code of the deployment"
    required: true
  resource_group:
    description: "Resource group name"
    required: true
  approval_url:
    description: "URL for approval action (staging only)"
    required: false
    default: ""
  rollback_url:
    description: "URL for rollback action (prod only)"
    required: false
    default: ""
  github_token:
    description: "GitHub token to be encoded and passed along"
    required: true
  teams_token:
    description: "Teams token to be encoded and passed along"
    required: true
  github_logic_app_url:
    description: "GitHub Logic App URL (used to build the approvalUrl)"
    required: true
  title:
    description: "Title for the notification"
    required: true
  color:
    description: "Color for the notification card"
    required: false
    default: "0076D7"
  change_summary:
    description: "Summary of changes being deployed"
    required: false
    default: ""
  deployment_id:
    description: "Deployment ID (required for approvalUrl)"
    required: false
    default: ""
  artifact_id:
    description: "Artifact ID (required for approvalUrl)"
    required: false
    default: ""
  run_id:
    description: "Run ID (required for approvalUrl)"
    required: false
    default: ""
  # New metadata inputs
  version:
    description: "Package version from package.json"
    required: false
    default: ""
  author:
    description: "Package author from package.json"
    required: false
    default: ""
  repository:
    description: "Package repository from package.json"
    required: false
    default: ""
  pr_description:
    description: "Pull Request description if available"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Checkout Repository for Template
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Read and Substitute Template
      shell: bash
      id: build_payload
      run: |
        # Read the JSON template file
        TEMPLATE=$(cat "$(pwd)/${{ inputs.template_path }}")
        echo "Template contents:"
        echo "$TEMPLATE"
    
        # Use input values and set default for color if empty
        color="${{ inputs.color }}"
        if [ -z "$color" ]; then
          color="0076D7"
        fi
    
        webhook_url="${{ inputs.webhook_url }}"
        location_code="${{ inputs.location_code }}"
        resource_group="${{ inputs.resource_group }}"
        environment="${{ inputs.environment }}"
        branch="${{ inputs.branch }}"
        message="${{ inputs.message }}"
        title="${{ inputs.title }}"
        deployment_url="${{ inputs.deployment_url }}"
        change_summary="${{ inputs.change_summary }}"
        deployment_id="${{ inputs.deployment_id }}"
        artifact_id="${{ inputs.artifact_id }}"
        run_id="${{ inputs.run_id }}"
    
        # New metadata variables
        version="${{ inputs.version }}"
        author="${{ inputs.author }}"
        repository="${{ inputs.repository }}"
        pr_description="${{ inputs.pr_description }}"
    
        # Helper function to escape special characters and newlines for sed substitution
        escape() {
          # Replace / and & with escaped versions and convert newlines to spaces.
          printf '%s' "$1" | sed -e 's/[\/&]/\\&/g' -e ':a;N;$!ba;s/\n/ /g'
        }
    
        # Escape variables that may contain special characters or newlines
        escaped_webhook_url=$(escape "$webhook_url")
        escaped_location_code=$(escape "$location_code")
        escaped_resource_group=$(escape "$resource_group")
        escaped_environment=$(escape "$environment")
        escaped_branch=$(escape "$branch")
        escaped_message=$(escape "$message")
        escaped_title=$(escape "$title")
        escaped_deployment_url=$(escape "$deployment_url")
        escaped_change_summary=$(escape "$change_summary")
        escaped_version=$(escape "$version")
        escaped_author=$(escape "$author")
        escaped_repository=$(escape "$repository")
        escaped_pr_description=$(escape "$pr_description")
        rollback_url="${{ inputs.rollback_url }}"
    
        # Encode tokens
        encodedGitHubToken=$(echo "${{ inputs.github_token }}" | base64)
        encodedTeamsToken=$(echo "${{ inputs.teams_token }}" | base64)
    
        # Construct approval URL using github_logic_app_url input
        if [ -n "${{ inputs.github_logic_app_url }}" ]; then
          base_url="${{ inputs.github_logic_app_url }}"
          # Remove placeholder tokens if present
          base_url="${base_url//\{\{approvalUrl\}\}/}"
          # Choose proper connector based on the presence of '?'
          if [[ "$base_url" == *"?"* ]]; then
            connector="&"
          else
            connector="?"
          fi
          # Ensure required parameters are provided
          if [ -z "$deployment_id" ] || [ -z "$artifact_id" ] || [ -z "$run_id" ]; then
            echo "Error: deployment_id, artifact_id, and run_id are required for constructing approval URL"
            exit 1
          fi
          encoded_token=$(echo "$encodedGitHubToken" | jq -sRr @uri)
          encoded_changes=$(echo "$change_summary" | jq -sRr @uri)
          encoded_deployment_id=$(echo "$deployment_id" | jq -sRr @uri)
          encoded_artifact_id=$(echo "$artifact_id" | jq -sRr @uri)
          encoded_run_id=$(echo "$run_id" | jq -sRr @uri)
          approval_url="${base_url}${connector}token=${encoded_token}&changes=${encoded_changes}&deploymentId=${encoded_deployment_id}&artifactId=${encoded_artifact_id}&runId=${encoded_run_id}"
          # Escape ampersands for sed
          escaped_approval_url=$(printf '%s' "$approval_url" | sed 's/&/\\&/g')
        else
          echo "Error: github_logic_app_url is required for approval URL"
          exit 1
        fi
    
        echo "Computed approval URL: $approval_url"
    
        # Use a single sed command with semicolon-separated substitutions
        PAYLOAD=$(sed -e "s|{{teamsWebhookUrl}}|${escaped_webhook_url}|g; s|{{locationCode}}|${escaped_location_code}|g; s|{{resourceGroup}}|${escaped_resource_group}|g; s|{{environment}}|${escaped_environment}|g; s|{{branch}}|${escaped_branch}|g; s|{{message}}|${escaped_message}|g; s|{{title}}|${escaped_title}|g; s|{{color}}|$color|g; s|{{deploymentUrl}}|${escaped_deployment_url}|g; s|{{rollbackUrl}}|${rollback_url}|g; s|{{encodedToken}}|${encodedGitHubToken}|g; s|{{encodedTeamsToken}}|${encodedTeamsToken}|g; s|{{approvalUrl}}|${escaped_approval_url}|g; s|{{version}}|${escaped_version}|g; s|{{author}}|${escaped_author}|g; s|{{repository}}|${escaped_repository}|g; s|{{pr_description}}|${escaped_pr_description}|g" <<< "$TEMPLATE")
        
        # Collapse the JSON payload to a single line using jq -c
        COMPACT_PAYLOAD=$(echo "$PAYLOAD" | jq -c .)
        echo "Generated Payload:"
        echo "$COMPACT_PAYLOAD"
        
        # Write the compact payload to output for later steps
        {
          echo "payload<<EOF"
          echo "$COMPACT_PAYLOAD"
          echo "EOF"
        } >> $GITHUB_OUTPUT

    - name: Invoke Logic App HTTP Trigger
      shell: bash
      run: |
        echo "Invoking Logic App via HTTP trigger..."
        COMPACT_PAYLOAD=$(jq -c . <<< '${{ steps.build_payload.outputs.payload }}')
        echo "Payload to be sent:"
        echo "$COMPACT_PAYLOAD"
        echo "Logic App URL:"
        echo "${{ inputs.logic_app_url }}"
        RESPONSE=$(curl -s -w "\nHTTP_STATUS:%{http_code}" -X POST -H "Content-Type: application/json" \
          -d "$COMPACT_PAYLOAD" \
          "${{ inputs.logic_app_url }}")
        echo "Response from Logic App:"
        echo "$RESPONSE"
