name: "Logic App Notification"
description: "Invoke the Logic App HTTP trigger with a notification payload."

inputs:
  logic_app_url:
    description: "URL of the Logic App HTTP trigger endpoint"
    required: true
  title:
    description: "Title of the notification"
    required: true
  environment:
    description: "Deployment environment (e.g. staging, prod)"
    required: true
  deployment_url:
    description: "URL of the deployed site"
    required: true
  branch:
    description: "Branch that was deployed"
    required: true
  location_code:
    description: "Location code of the deployment"
    required: true
  resource_group:
    description: "Resource group name"
    required: true
  color:
    description: "Theme color for the notification (hex code)"
    required: false
    default: "0076D7"
  approval_url:
    description: "URL for approval action (staging only)"
    required: false
    default: ""
  rollback_url:
    description: "URL for rollback action (prod only)"
    required: false
    default: ""
  webhook_url:
    description: "Webhook URL for Teams notifications"
    required: false
    default: "https://phoenixvc568.webhook.office.com/webhookb2/17b0291f-b70b-4bdd-9266-f212ae03a2bd@7edf4423-ccb3-4275-bc80-64dae3ef0148/IncomingWebhook/3174ffcca3804d34ae923ba2e131f82e/a41dbcc0-67a6-4a23-bdec-b780dcebefa9/V2MOPWeKY7ywC8-iGptxHlSIZpwHVxw2FLAOAMU2N0hmM1"

runs:
  using: "composite"
  steps:
  - name: Build Payload with jq
    shell: bash
    id: build_payload
    run: |
      # Use jq's --arg to safely pass shell variables into a JSON object
      PAYLOAD=$(jq -n \
        --arg title "${{ inputs.title }}" \
        --arg environment "${{ inputs.environment }}" \
        --arg deploymentUrl "${{ inputs.deployment_url }}" \
        --arg branch "${{ inputs.branch }}" \
        --arg locationCode "${{ inputs.location_code }}" \
        --arg resourceGroup "${{ inputs.resource_group }}" \
        --arg color "${{ inputs.color }}" \
        --arg approvalUrl "${{ inputs.approval_url }}" \
        --arg rollbackUrl "${{ inputs.rollback_url }}" \
        --arg webhookUrl "${{ inputs.webhook_url }}" \
        '{
          title: $title,
          environment: $environment,
          deploymentUrl: $deploymentUrl,
          branch: $branch,
          locationCode: $locationCode,
          resourceGroup: $resourceGroup,
          color: $color,
          approvalUrl: $approvalUrl,
          rollbackUrl: $rollbackUrl,
          webhookUrl: $webhookUrl
        }'
      )

      echo "Generated Payload:"
      echo "$PAYLOAD" | jq .

      # Write the payload to GITHUB_OUTPUT (multiline-safe)
      echo "payload<<EOF" >> $GITHUB_OUTPUT
      echo "$PAYLOAD" >> $GITHUB_OUTPUT
      echo "EOF" >> $GITHUB_OUTPUT

  - name: Invoke Logic App HTTP Trigger
    shell: bash
    run: |
      echo "Invoking Logic App via HTTP trigger..."
      echo "${{ steps.build_payload.outputs.payload }}" | jq .
      curl -X POST \
        -H "Content-Type: application/json" \
        -d "$(echo '${{ steps.build_payload.outputs.payload }}' | jq -c .)" \
        "${{ inputs.logic_app_url }}"
