name: "Teams Notification"
description: "Send a notification to Microsoft Teams with deployment information using a file-based JSON template, encoding GitHub and Teams tokens."

inputs:
  logic_app_url:
    description: "URL of the Logic App HTTP trigger endpoint"
    required: true
  template_path:
    description: "Path to the JSON template file relative to the repository root"
    required: false
    default: ".github/actions/teams-notification/logic-app-teams-template.json"
  webhook_url:
    description: "Microsoft Teams webhook URL"
    required: false
    default: "https://phoenixvc568.webhook.office.com/webhookb2/..."
  message:
    description: "Notification message"
    required: true
  environment:
    description: "Deployment environment (e.g. staging, prod)"
    required: true
  deployment_url:
    description: "URL of the deployed site"
    required: true
  branch:
    description: "Branch that was deployed"
    required: true
  location_code:
    description: "Location code of the deployment"
    required: true
  resource_group:
    description: "Resource group name"
    required: true
  approval_url:
    description: "URL for approval action (staging only)"
    required: false
    default: ""
  rollback_url:
    description: "URL for rollback action (prod only)"
    required: false
    default: ""
  github_token:
    description: "GitHub token to be encoded and passed along"
    required: true
  teams_token:
    description: "Teams token to be encoded and passed along"
    required: true
  github_logic_app_url:
    description: "GitHub Logic App URL"
    required: true
  title:
    description: "Title for the notification"
    required: true
  color:
    description: "Color for the notification card"
    required: false
    default: "0076D7"
  change_summary:
    description: "Summary of changes being deployed"
    required: false
    default: ""
  deployment_id:
    description: "Deployment ID"
    required: false
    default: ""
  artifact_id:
    description: "Artifact ID"
    required: false
    default: ""
  run_id:
    description: "Run ID"
    required: false
    default: ""

runs:
  using: "composite"
  steps:

    - name: Checkout Repository for Template
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Read and Substitute Template
      shell: bash
      id: build_payload
      run: |
        encodedGitHubToken=$(echo "${{ inputs.github_token }}" | base64)
        encodedTeamsToken=$(echo "${{ inputs.teams_token }}" | base64)
        echo "Encoded GitHub token: $encodedGitHubToken"
        echo "Encoded Teams token: $encodedTeamsToken"

        # Read the JSON template file
        TEMPLATE=$(cat "$(pwd)/${{ inputs.template_path }}")
        echo "Template contents:"
        echo "$TEMPLATE"

        color="${{ inputs.color }}"
        if [ -z "$color" ]; then
          color="0076D7"
        fi

        # Validate required variables
        webhook_url="${{ inputs.webhook_url }}"
        location_code="${{ inputs.location_code }}"
        resource_group="${{ inputs.resource_group }}"
        environment="${{ inputs.environment }}"
        branch="${{ inputs.branch }}"
        message="${{ inputs.message }}"
        title="${{ inputs.title }}"
        deployment_url="${{ inputs.deployment_url }}"

        # Get additional parameters
        change_summary="${{ inputs.change_summary }}"
        deployment_id="${{ inputs.deployment_id }}"
        artifact_id="${{ inputs.artifact_id }}"
        run_id="${{ inputs.run_id }}"

        # Construct approval URL
        if [ -n "${{ inputs.github_logic_app_url }}" ]; then
          # Remove all instances of the placeholder tokens
          base_url=$(echo "${{ inputs.github_logic_app_url }}" | sed 's|{{approvalUrl}}||g')

          # Determine the connector: if the base URL already has a '?', use '&', else use '?'
          if [[ "$base_url" == *"?"* ]]; then
            connector="&"
          else
            connector="?"
          fi

          # Ensure required parameters are available
          if [ -z "$deployment_id" ] || [ -z "$artifact_id" ] || [ -z "$run_id" ]; then
            echo "Error: deployment_id, artifact_id, and run_id are required for staging environment"
            exit 1
          fi

          # URL encode each parameter separately
          encoded_token=$(echo "$encodedGitHubToken" | jq -sRr @uri)
          encoded_changes=$(echo "$change_summary" | jq -sRr @uri)
          encoded_deployment_id=$(echo "$deployment_id" | jq -sRr @uri)
          encoded_artifact_id=$(echo "$artifact_id" | jq -sRr @uri)
          encoded_run_id=$(echo "$run_id" | jq -sRr @uri)

          # Append our parameters using the correct connector
          approval_url="${base_url}${connector}token=${encoded_token}&changes=${encoded_changes}&deploymentId=${encoded_deployment_id}&artifactId=${encoded_artifact_id}&runId=${encoded_run_id}"
        else
          echo "Error: github_logic_app_url is required for approval URL"
          exit 1
        fi

        required_vars=(
          "webhook_url"
          "location_code"
          "resource_group"
          "environment"
          "branch"
          "message"
          "title"
          "deployment_url"
          "encodedGitHubToken"
          "encodedTeamsToken"
        )

        for var in "${required_vars[@]}"; do
          if [ -z "${!var}" ]; then
            echo "Error: Required variable $var is empty"
            exit 1
          fi
        done

        # Substitute placeholders in the template
        PAYLOAD=$(echo "$TEMPLATE" | sed \
          -e "s|{{teamsWebhookUrl}}|${{ inputs.webhook_url }}|g" \
          -e "s|{{locationCode}}|${{ inputs.location_code }}|g" \
          -e "s|{{resourceGroup}}|${{ inputs.resource_group }}|g" \
          -e "s|{{environment}}|${{ inputs.environment }}|g" \
          -e "s|{{branch}}|${{ inputs.branch }}|g" \
          -e "s|{{message}}|${{ inputs.message }}|g" \
          -e "s|{{title}}|${{ inputs.title }}|g" \
          -e "s|{{color}}|$color|g" \
          -e "s|{{deploymentUrl}}|${{ inputs.deployment_url }}|g" \
          -e "s|{{rollbackUrl}}|${{ inputs.rollback_url }}|g" \
          -e "s|{{encodedToken}}|$encodedGitHubToken|g" \
          -e "s|{{encodedTeamsToken}}|$encodedTeamsToken|g" \
          -e "s|{{approvalUrl}}|${approval_url}|g"
        )
        echo "Generated Payload:"
        echo "$PAYLOAD"

        # Write the payload as a multi-line output
        echo "payload<<EOF" >> $GITHUB_OUTPUT
        echo "$PAYLOAD" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Invoke Logic App HTTP Trigger
      shell: bash
      run: |
        echo "Invoking Logic App via HTTP trigger..."

        # Use jq to parse and compact JSON safely
        COMPACT_PAYLOAD=$(jq -c . <<< '${{ steps.build_payload.outputs.payload }}')

        echo "Payload to be sent:"
        echo "$COMPACT_PAYLOAD"

        RESPONSE=$(curl -s -w "\nHTTP_STATUS:%{http_code}" -X POST -H "Content-Type: application/json" \
          -d "$COMPACT_PAYLOAD" \
          "${{ inputs.logic_app_url }}")

        echo "Response from Logic App:"
        echo "$RESPONSE"
