name: "Teams Notification"
description: "Send a notification to Microsoft Teams with deployment information using a file-based JSON template."

inputs:
  logic_app_url:
    description: "URL of the Logic App HTTP trigger endpoint"
    required: true
  template_path:
    description: "Path to the JSON template file relative to the repository root"
    required: false
    default: ".github/actions/teams-notification/logic-app-template.json"
  webhook_url:
    description: "Microsoft Teams webhook URL"
    required: false
    default: "https://phoenixvc568.webhook.office.com/webhookb2/17b0291f-b70b-4bdd-9266-f212ae03a2bd@7edf4423-ccb3-4275-bc80-64dae3ef0148/IncomingWebhook/3174ffcca3804d34ae923ba2e131f82e/a41dbcc0-67a6-4a23-bdec-b780dcebefa9/V2MOPWeKY7ywC8-iGptxHlSIZpwHVxw2FLAOAMU2N0hmM1"
  message:
    description: "Notification message"
    required: true
  environment:
    description: "Deployment environment (e.g. staging, prod)"
    required: true
  deployment_url:
    description: "URL of the deployed site"
    required: true
  branch:
    description: "Branch that was deployed"
    required: true
  location_code:
    description: "Location code of the deployment"
    required: true
  resource_group:
    description: "Resource group name"
    required: true
  approval_url:
    description: "URL for approval action (staging only)"
    required: false
    default: ""
  rollback_url:
    description: "URL for rollback action (prod only)"
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Checkout Repository for Template
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Read Template
      shell: bash
      id: build_payload
      run: |
        TEMPLATE=$(cat "$(pwd)/${{ inputs.template_path }}")
        echo "Template contents:"
        echo "$TEMPLATE"
        echo "payload<<EOF" >> $GITHUB_OUTPUT
        echo "$TEMPLATE" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Invoke Logic App HTTP Trigger
      shell: bash
      run: |
        echo "Invoking Logic App via HTTP trigger..."
        RESPONSE=$(curl -s -w "\nHTTP_STATUS:%{http_code}" -X POST -H "Content-Type: application/json" -d "$(echo "${{ steps.build_payload.outputs.payload }}" | jq -c .)" "${{ inputs.logic_app_url }}")
        echo "Response from Logic App:"
        echo "$RESPONSE"
