name: "Teams Notification"
description: "Send a notification to Microsoft Teams with deployment information using a file-based JSON template, encoding GitHub and Teams tokens."

inputs:
  logic_app_url:
    description: "URL of the Logic App HTTP trigger endpoint"
    required: true
  template_path:
    description: "Path to the JSON template file relative to the repository root"
    required: false
    default: ".github/actions/teams-notification/logic-app-teams-template.json"
  webhook_url:
    description: "Microsoft Teams webhook URL"
    required: false
    default: "https://phoenixvc568.webhook.office.com/webhookb2/..."
  message:
    description: "Notification message"
    required: true
  environment:
    description: "Deployment environment (e.g. staging, prod)"
    required: true
  deployment_url:
    description: "URL of the deployed site"
    required: true
  branch:
    description: "Branch that was deployed"
    required: true
  location_code:
    description: "Location code of the deployment"
    required: true
  resource_group:
    description: "Resource group name"
    required: true
  approval_url:
    description: "URL for approval action (staging only)"
    required: false
    default: ""
  rollback_url:
    description: "URL for rollback action (prod only)"
    required: false
    default: ""
  github_token:
    description: "GitHub token to be encoded and passed along"
    required: true
  teams_token:
    description: "Teams token to be encoded and passed along"
    required: true
  github_logic_app_url:
    description: "GitHub Logic App URL"
    required: true
  title:
    description: "Title for the notification"
    required: true
  color:
    description: "Color for the notification card"
    required: false
    default: "0076D7"
  change_summary:
    description: "Summary of changes being deployed"
    required: false
    default: ""
  deployment_id:
    description: "Deployment ID"
    required: false
    default: ""
  artifact_id:
    description: "Artifact ID"
    required: false
    default: ""
  run_id:
    description: "Run ID"
    required: false
    default: ""

runs:
  using: "composite"
  steps:

    - name: Checkout Repository for Template
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Read and Substitute Template
      shell: bash
      id: build_payload
      run: |
        # Hardcoded payload (adjust values if needed)
        PAYLOAD='{
          "teamsWebhookUrl": "https://test.com",
          "locationCode": "euw",
          "resourceGroup": "staging-euw-rg-phoenixvc-website",
          "environment": "staging",
          "branch": "refs/pull/25/merge",
          "message": "The deployment to the STAGING environment has completed successfully. Please review the deployment and take any necessary actions.",
          "title": "Staging Deployment Complete",
          "color": "0076D7",
          "deploymentUrl": "https://jolly-pebble-05d585a03.6.azurestaticapps.net",
          "approvalUrl": "https://test.com",
          "rollbackUrl": "",
          "encodedToken": "Z2hzX1FEOHlQRUt0bGN5TE44WkV0Y1ZqM0dhcEZUclFQYTN0ZXRtRwo=",
          "encodedTeamsToken": "Cg==",
          "adaptiveCard": {
            "$schema": "http://adaptivecards.io/schemas/adaptive-card.json",
            "type": "AdaptiveCard",
            "version": "1.2",
            "body": [
              {
                "type": "TextBlock",
                "text": "Phoenix VC staging Deployment Notification",
                "weight": "Bolder",
                "size": "Large"
              },
              {
                "type": "TextBlock",
                "text": "Deployment to staging Completed",
                "wrap": true
              },
              {
                "type": "FactSet",
                "facts": [
                  { "title": "Environment", "value": "staging" },
                  { "title": "Location", "value": "euw" },
                  { "title": "Resource Group", "value": "staging-euw-rg-phoenixvc-website" },
                  { "title": "Site URL", "value": "https://jolly-pebble-05d585a03.6.azurestaticapps.net" }
                ]
              },
              {
                "type": "TextBlock",
                "text": "The deployment to staging has completed successfully. Please review the details above and take any necessary actions.",
                "wrap": true
              }
            ],
            "actions": [
              {
                "type": "Action.OpenUrl",
                "title": "View Site",
                "url": "https://jolly-pebble-05d585a03.6.azurestaticapps.net"
              },
              {
                "type": "Action.OpenUrl",
                "title": "Approve Production Deployment",
                "url": "https://test.com"
              },
              {
                "type": "Action.OpenUrl",
                "title": "Rollback Deployment",
                "url": "https://test.com"
              }
            ]
          }
        }'
        echo "Generated Payload:"
        echo "$PAYLOAD"
        echo "payload<<EOF" >> $GITHUB_OUTPUT
        echo "$PAYLOAD" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

    - name: Invoke Logic App HTTP Trigger
      shell: bash
      run: |
        echo "Invoking Logic App via HTTP trigger..."

        # Use jq to parse and compact JSON safely
        COMPACT_PAYLOAD=$(jq -c . <<< '${{ steps.build_payload.outputs.payload }}')

        echo "Payload to be sent:"
        echo "$COMPACT_PAYLOAD"
        echo "Log app url:"
        echo "${{ inputs.logic_app_url }}"

        RESPONSE=$(curl -s -w "\nHTTP_STATUS:%{http_code}" -X POST -H "Content-Type: application/json" \
          -d "$COMPACT_PAYLOAD" \
          "${{ inputs.logic_app_url }}")

        echo "Response from Logic App:"
        echo "$RESPONSE"
