name: "Deploy Azure Resources"
description: "Deploys infrastructure resources for a given environment"

inputs:
  environment:
    description: "The deployment environment (staging or prod)"
    required: true
  azure_subscription_id:
    description: "Azure Subscription ID"
    required: true
  azure_credentials:
    description: "Azure credentials for authentication"
    required: true
  location_code:
    description: "Location code for resource naming"
    required: true
  repository:
    description: "GitHub repository to use"
    required: true
  token:
    description: "GitHub token"
    required: true

outputs:
  staticSiteUrl:
    description: "URL of the deployed Static Web App"
    value: ${{ steps.deploy.outputs.staticSiteUrl }}
  teamsLogicAppUrl:
    description: "URL of the deployed Teams Logic App"
    value: ${{ steps.retrieve_logic_url.outputs.logicAppUrl }}
  githubLogicAppUrl:
    description: "URL of the deployed GitHub Logic App"
    value: ${{ steps.retrieve_github_logic_url.outputs.githubLogicAppUrl }}

runs:
  using: "composite"
  steps:
    - name: Validate Azure Subscription ID
      shell: bash
      run: |
        if [[ -z "${{ inputs.azure_subscription_id }}" ]]; then
          echo "❌ ERROR: AZURE_SUBSCRIPTION_ID is empty!"
          exit 1
        else
          echo "✅ AZURE_SUBSCRIPTION_ID: ${{ inputs.azure_subscription_id }}"
        fi

    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repository }}
        token: ${{ inputs.token }}
        fetch-depth: 0

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ inputs.azure_credentials }}

    - name: Make deploy script executable
      shell: bash
      run: chmod +x ./scripts/deployment/deploy.sh

    - name: Run Resource Deployment Script
      shell: bash
      run: |
        ./scripts/deployment/deploy.sh --env ${{ inputs.environment }}
      env:
        ENVIRONMENT: ${{ inputs.environment }}
        RG_NAME: ${{ inputs.environment }}-${{ inputs.location_code }}-rg-phoenixvc-website
        SWA_NAME: ${{ inputs.environment }}-${{ inputs.location_code }}-swa-phoenixvc-website
        AZURE_SUBSCRIPTION_ID: ${{ inputs.azure_subscription_id }}

    - name: Retrieve Teams Logic App Trigger URL
      id: retrieve_logic_url
      shell: bash
      run: |
        # Define Variables for Teams Logic App
        subscriptionId="${{ inputs.azure_subscription_id }}"
        resourceGroupName="${{ inputs.environment }}-${{ inputs.location_code }}-rg-phoenixvc-website"
        logicAppName="${{ inputs.environment }}-${{ inputs.location_code }}-la-phoenixvc"
        triggerName="manual"

        echo "Retrieving Teams Logic App URL for: $logicAppName"
        url="https://management.azure.com/subscriptions/$subscriptionId/resourceGroups/$resourceGroupName/providers/Microsoft.Logic/workflows/$logicAppName/triggers/$triggerName/listCallbackUrl?api-version=2019-05-01"
        echo "API URL: $url"
        response=$(az rest --method POST --uri "$url" --query "value" -o tsv)
        if [[ -n "$response" ]]; then
          echo "✅ Retrieved Teams Logic App URL: $response"
          echo "logicAppUrl=$response" >> "$GITHUB_OUTPUT"
        else
          echo "⚠️ Teams Logic App URL could not be retrieved"
          echo "logicAppUrl=" >> "$GITHUB_OUTPUT"
        fi

    - name: Retrieve GitHub Logic App Trigger URL
      id: retrieve_github_logic_url
      shell: bash
      run: |
        # Define Variables for GitHub Logic App
        subscriptionId="${{ inputs.azure_subscription_id }}"
        resourceGroupName="${{ inputs.environment }}-${{ inputs.location_code }}-rg-phoenixvc-website"
        logicAppName="${{ inputs.environment }}-${{ inputs.location_code }}-la-github"
        triggerName="manual"

        echo "Retrieving GitHub Logic App URL for: $logicAppName"
        url="https://management.azure.com/subscriptions/$subscriptionId/resourceGroups/$resourceGroupName/providers/Microsoft.Logic/workflows/$logicAppName/triggers/$triggerName/listCallbackUrl?api-version=2019-05-01"
        echo "API URL: $url"
        response=$(az rest --method POST --uri "$url" --query "value" -o tsv)
        if [[ -n "$response" ]]; then
          echo "✅ Retrieved GitHub Logic App URL: $response"
          echo "githubLogicAppUrl=$response" >> "$GITHUB_OUTPUT"
        else
          echo "⚠️ GitHub Logic App URL could not be retrieved"
          echo "githubLogicAppUrl=" >> "$GITHUB_OUTPUT"
        fi
