name: "Deploy Azure Resources"
description: "Deploys infrastructure resources for a given environment"

inputs:
  environment:
    description: "The deployment environment (staging or prod)"
    required: true
  azure_subscription_id:
    description: "Azure Subscription ID"
    required: true
  azure_credentials:
    description: "Azure credentials for authentication"
    required: true
  location_code:
    description: "Location code for resource naming"
    required: true
  repository:
    description: "GitHub repository to use"
    required: true
  token:
    description: "GitHub token"
    required: true
  skip_logic_apps:
    description: "If true, skip retrieving Logic App URLs"
    required: false
    default: "false"

outputs:
  staticSiteUrl:
    description: "URL of the deployed Static Web App"
    value: ${{ steps.deploy.outputs.staticSiteUrl }}
runs:
  using: "composite"
  steps:
    - name: Debug Environment Variables
      shell: bash
      run: |
        echo "==========================="
        echo "🔍 DEBUG: Environment Variables"
        echo "==========================="
        echo "Environment: ${{ inputs.environment }}"
        echo "Location Code: ${{ inputs.location_code }}"
        echo "Repository: ${{ inputs.repository }}"
        echo "Current Directory: $(pwd)"
        echo "Directory Contents: $(ls -la)"
        echo "==========================="

    - name: Validate Azure Subscription ID
      shell: bash
      run: |
        if [[ -z "${{ inputs.azure_subscription_id }}" ]]; then
          echo "❌ ERROR: AZURE_SUBSCRIPTION_ID is empty!"
          exit 1
        else
          echo "✅ AZURE_SUBSCRIPTION_ID: ${{ inputs.azure_subscription_id }}"
        fi

    # Improved step to check GitHub API for artifacts with retry mechanism
    - name: Check GitHub API for Artifacts
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.token }}
      run: |
        echo "==========================="
        echo "🔍 DEBUG: Checking GitHub API for Artifacts"
        echo "==========================="

        # Get the current run ID
        RUN_ID="${{ github.run_id }}"
        REPO="${{ inputs.repository }}"

        echo "Current Run ID: $RUN_ID"
        echo "Repository: $REPO"

        # Function to check artifacts with proper error handling
        check_artifacts() {
          # Use curl with proper error handling
          echo "Checking artifacts for run ID: $RUN_ID"

          # Make the API request
          response=$(curl -s -w "\n%{http_code}" -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            "https://api.github.com/repos/$REPO/actions/runs/$RUN_ID/artifacts")

          # Extract status code (last line) and response body
          status_code=$(echo "$response" | tail -n1)
          body=$(echo "$response" | sed '$d')

          echo "API Status Code: $status_code"

          # Check for API errors
          if [[ "$status_code" != "200" ]]; then
            echo "❌ GitHub API Error: HTTP $status_code"
            echo "Response body:"
            echo "$body"
            return 1
          fi

          # Check if the response is valid JSON
          if ! echo "$body" | jq . > /dev/null 2>&1; then
            echo "❌ Invalid JSON response"
            echo "$body"
            return 1
          fi

          # Parse artifact count
          artifact_count=$(echo "$body" | jq -r '.total_count')
          echo "Total artifacts found: $artifact_count"

          if [[ "$artifact_count" -gt 0 ]]; then
            echo "Available artifacts:"
            echo "$body" | jq -r '.artifacts[] | "- " + .name'

            # Check specifically for web-dist artifacts
            web_dist_artifacts=$(echo "$body" | jq -r '.artifacts[] | select(.name | startswith("web-dist")) | .name')
            if [[ -n "$web_dist_artifacts" ]]; then
              echo "Found web-dist artifacts:"
              echo "$web_dist_artifacts"
              return 0
            else
              echo "No web-dist artifacts found in this run."
              return 2
            fi
          else
            echo "No artifacts found for run ID: $RUN_ID"
            return 2
          fi
        }

        # Try checking for artifacts with retries
        MAX_RETRIES=5
        RETRY_DELAY=10
        ATTEMPT=1
        SUCCESS=false

        while [[ $ATTEMPT -le $MAX_RETRIES ]]; do
          echo "Attempt $ATTEMPT of $MAX_RETRIES to check for artifacts..."

          if check_artifacts; then
            echo "✅ Successfully found artifacts on attempt $ATTEMPT"
            SUCCESS=true
            break
          else
            echo "⚠️ Attempt $ATTEMPT failed. Waiting $RETRY_DELAY seconds before retrying..."
            sleep $RETRY_DELAY
            ATTEMPT=$((ATTEMPT + 1))
            # Increase delay for subsequent retries
            RETRY_DELAY=$((RETRY_DELAY + 5))
          fi
        done

        if [[ "$SUCCESS" != "true" ]]; then
          echo "⚠️ Warning: Could not find artifacts after $MAX_RETRIES attempts."
          echo "This is not a critical error, continuing with deployment..."
        fi

        # Also check the workflow runs to ensure we have the correct run ID
        echo "Checking workflow runs for repository: $REPO"
        RUNS_RESPONSE=$(curl -sSL -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          "https://api.github.com/repos/$REPO/actions/runs?per_page=5")

        echo "Recent workflow runs:"
        if echo "$RUNS_RESPONSE" | jq . > /dev/null 2>&1; then
          echo "$RUNS_RESPONSE" | jq -r '.workflow_runs[] | "ID: " + (.id | tostring) + ", Status: " + .status + ", Conclusion: " + (.conclusion // "running")'
        else
          echo "Could not parse workflow runs response"
          echo "$RUNS_RESPONSE" | grep -o '"id":[0-9]*' | cut -d ':' -f2
        fi

        echo "==========================="

    - name: Check for Deployment Script
      shell: bash
      run: |
        echo "==========================="
        echo "🔍 DEBUG: Checking for deployment script"
        echo "==========================="
        if [ -f "./scripts/deployment/deploy.sh" ]; then
          echo "✅ Deployment script found at ./scripts/deployment/deploy.sh"
          ls -la ./scripts/deployment/
        else
          echo "❌ ERROR: Deployment script not found at ./scripts/deployment/deploy.sh"
          echo "Current directory: $(pwd)"
          echo "Directory structure:"
          find . -type f -name "deploy.sh" 2>/dev/null || echo "No deploy.sh found"
          exit 1
        fi
        echo "==========================="

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ inputs.azure_credentials }}

    - name: Make deploy script executable
      shell: bash
      run: |
        echo "Making deploy script executable..."
        chmod +x ./scripts/deployment/deploy.sh
        echo "File permissions after chmod:"
        ls -la ./scripts/deployment/deploy.sh

    - name: Debug Before Deployment
      shell: bash
      run: |
        echo "==========================="
        echo "🔍 DEBUG: Before Deployment"
        echo "==========================="
        echo "Command to run: bash -x ./scripts/deployment/deploy.sh --env ${{ inputs.environment }}"
        echo "Environment variables:"
        echo "ENVIRONMENT: ${{ inputs.environment }}"
        echo "RG_NAME: ${{ inputs.environment }}-${{ inputs.location_code }}-rg-phoenixvc-website"
        echo "SWA_NAME: ${{ inputs.environment }}-${{ inputs.location_code }}-swa-phoenixvc-website"
        echo "==========================="

    - name: Run Resource Deployment Script
      id: deploy
      shell: bash
      run: |
        echo "==========================="
        echo "🔍 DEBUG: Starting Deployment Script"
        echo "==========================="

        # Run deployment script with error handling
        set +e  # Don't exit on error to capture output
        OUTPUT=$(bash -x ./scripts/deployment/deploy.sh --env ${{ inputs.environment }} 2>&1)
        DEPLOY_EXIT_CODE=$?
        set -e  # Resume exit on error

        echo "$OUTPUT"

        if [ $DEPLOY_EXIT_CODE -ne 0 ]; then
          echo "❌ ERROR: Deployment script failed with exit code $DEPLOY_EXIT_CODE"
          echo "Last 50 lines of output:"
          echo "$OUTPUT" | tail -n 50
          echo "==========================="
          exit $DEPLOY_EXIT_CODE
        fi

        echo "✅ Deployment script completed successfully"
        echo "==========================="

        # Explicitly retrieve the Static Web App URL after deployment
        echo "🔍 DEBUG: Retrieving Static Web App URL"
        STATIC_SITE_URL=$(az staticwebapp show \
          --name "${{ inputs.environment }}-${{ inputs.location_code }}-swa-phoenixvc-website" \
          --resource-group "${{ inputs.environment }}-${{ inputs.location_code }}-rg-phoenixvc-website" \
          --query "defaultHostname" \
          --output tsv)

        if [[ -n "$STATIC_SITE_URL" ]]; then
          FULL_URL="https://$STATIC_SITE_URL"
          echo "✅ Static Web App URL: $FULL_URL"
          echo "staticSiteUrl=$FULL_URL" >> "$GITHUB_OUTPUT"
        else
          echo "❌ Failed to retrieve Static Web App URL."
          echo "staticSiteUrl=" >> "$GITHUB_OUTPUT"
          exit 1
        fi
      env:
        ENVIRONMENT: ${{ inputs.environment }}
        RG_NAME: ${{ inputs.environment }}-${{ inputs.location_code }}-rg-phoenixvc-website
        SWA_NAME: ${{ inputs.environment }}-${{ inputs.location_code }}-swa-phoenixvc-website
        AZURE_SUBSCRIPTION_ID: ${{ inputs.azure_subscription_id }}
        GITHUB_TOKEN: ${{ inputs.token }}


    - name: Debug Summary
      shell: bash
      run: |
        echo "==========================="
        echo "🔍 DEBUG: Deployment Summary"
        echo "==========================="
        echo "Environment: ${{ inputs.environment }}"
        echo "Resource Group: ${{ inputs.environment }}-${{ inputs.location_code }}-rg-phoenixvc-website"
        echo "Static Web App: ${{ inputs.environment }}-${{ inputs.location_code }}-swa-phoenixvc-website"
        echo "==========================="
