name: "Setup Azure Deployment Environment"
description: "Makes the deploy script executable, verifies Azure CLI, sets the subscription ID, and logs in to Azure."

inputs:
  azure_credentials:
    description: "Azure credentials in JSON format."
    required: true
  token:
    description: "The token to use for checkout."
    required: true
  repository:
    description: "The repository to checkout and setup for deployment."
    required: false
    default: "phoenixvc/PhoenixVC-Website"
  ref:
    description: "Branch or commit to check out."
    required: false
    default: "main"
  fetchDepth:
    description: "Depth of the checkout. 0 = full history."
    required: false
    default: "0"

outputs:
  azure_cli_version:
    description: "The version of the Azure CLI detected."

runs:
  using: "composite"
  steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.repository }}
        ref: ${{ inputs.ref }}
        token: ${{ inputs.token }}
        fetch-depth: ${{ inputs.fetchDepth }}

    - name: Make deploy script executable
      run: chmod +x ./scripts/deployment/deploy.sh
      shell: bash

    - name: Set up Azure CLI
      id: cli
      run: |
        az version > cli_version.txt
        cat cli_version.txt
      shell: bash

    - name: Set up Azure Subscription ID
      run: echo "AZURE_SUBSCRIPTION_ID=${{ inputs.azure_credentials.subscriptionId }}" >> $GITHUB_ENV
      shell: bash

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ inputs.azure_credentials }}

    - name: Set Azure CLI Version Output
      run: |
        cli_version=$(cat cli_version.txt | jq -c '.')
        echo "azure_cli_version=${cli_version}" >> $GITHUB_OUTPUT
      shell: bash
