name: "Setup Azure Deployment Environment"
description: "Makes the deploy script executable, verifies Azure CLI, sets the subscription ID, and logs in to Azure."
inputs:
  azure_subscription_id:
    description: "The Azure Subscription ID to use for the deployment."
    required: true
  azure_credentials:
    description: "Azure credentials in JSON format."
    required: true
  token:
    description: "The token to use for checkout"
    required: false
outputs:
  azure_cli_version:
    description: "The version of the Azure CLI detected."
runs:
  using: "composite"
  steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        token: ${{ inputs.token }}

    - name: Make deploy script executable
      run: chmod +x ./scripts/deployment/deploy.sh
      shell: bash

    - name: Set up Azure CLI
      id: cli
      run: |
        az version > cli_version.txt
        cat cli_version.txt
      shell: bash

    - name: Set up Azure Subscription ID
      run: echo "AZURE_SUBSCRIPTION_ID=${{ inputs.azure_subscription_id }}" >> $GITHUB_ENV
      shell: bash

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ inputs.azure_credentials }}

    - name: Set Azure CLI Version Output  
      run: |
        cli_version=$(cat cli_version.txt | jq -c '.')
        echo "azure_cli_version=${cli_version}" >> $GITHUB_OUTPUT
      shell: bash
