name: "SWA Deploy"
description: "Deploy site via SWA CLI with Azure CLI fallback from a downloaded artifact."
inputs:
  artifact-name:
    description: "The name of the artifact to download"
    required: true
  app-name:
    description: "The SWA app name"
    required: true
  resource-group:
    description: "The resource group for the SWA app"
    required: true
  env:
    description: "The deployment environment (e.g. staging, prod)"
    required: true
  artifact-path:
    description: "Local path to download the artifact to"
    required: false
    default: "./build-artifact"
  azure_credentials:
    description: "Azure credentials for authentication"
    required: true
  deployment_token:
    description: "SWA deployment token"
    required: true
runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Download Web App Artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ inputs.artifact-path }}

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Azure Static Web Apps CLI
      shell: bash
      run: |
        echo "Installing SWA CLI..."
        npm install --no-fund --no-audit --loglevel=error -g @azure/static-web-apps-cli

    # Try SWA CLI first as the primary method
    - name: Deploy Site via SWA CLI (Primary Method)
      id: swa_cli_deploy
      shell: bash
      run: |
        echo "Deploying to ${{ inputs.env }} using SWA CLI from artifact..."
        # Add sleep to ensure file system is ready
        sleep 2
        # Use chmod to ensure executable permissions
        chmod -R 755 ${{ inputs.artifact-path }}
        
        # Try deployment with explicit token
        swa deploy "${{ inputs.artifact-path }}" \
          --deployment-token "${{ inputs.deployment_token }}" \
          --env "${{ inputs.env }}" || echo "swa_cli_failed=true" >> $GITHUB_OUTPUT
      continue-on-error: true

    # Only try Azure CLI if SWA CLI fails
    - name: Azure Login (Fallback)
      if: ${{ steps.swa_cli_deploy.outputs.swa_cli_failed == 'true' }}
      uses: azure/login@v1
      with:
        creds: ${{ inputs.azure_credentials }}
        
    - name: Deploy using Azure CLI (Fallback Method)
      if: ${{ steps.swa_cli_deploy.outputs.swa_cli_failed == 'true' }}
      shell: bash
      run: |
        echo "Installing Azure CLI extension for Static Web Apps..."
        az extension add --name static-web-apps --only-show-errors || echo "Extension installation failed, continuing..."
        
        echo "Deploying to ${{ inputs.env }} environment using Azure CLI..."
        az staticwebapps deploy \
          --name ${{ inputs.app-name }} \
          --resource-group ${{ inputs.resource-group }} \
          --source ${{ inputs.artifact-path }} \
          --env ${{ inputs.env }} \
          --token "${{ inputs.deployment_token }}" \
          --verbose
