name: "SWA Deploy"
description: "Deploy site via SWA CLI with Azure CLI fallback from a downloaded artifact."
inputs:
  artifact-name:
    description: "The name of the artifact to download"
    required: true
  app-name:
    description: "The SWA app name"
    required: true
  resource-group:
    description: "The resource group for the SWA app"
    required: true
  env:
    description: "The deployment environment (e.g. staging, prod)"
    required: true
  artifact-path:
    description: "Local path to download the artifact to"
    required: false
    default: "./build-artifact"
  azure_credentials:
    description: "Azure credentials for authentication"
    required: true
  deployment_token:
    description: "SWA deployment token"
    required: true
outputs:
  deployment_url:
    description: "The URL of the deployed application"
    value: ${{ steps.get_deployment_url.outputs.url }}
runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Download Web App Artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ inputs.artifact-path }}

    # Login to Azure first - this will prevent the interactive login prompt
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ inputs.azure_credentials }}

    # Install Azure CLI extension for Static Web Apps
    - name: Install Azure CLI extensions
      shell: bash
      run: |
        echo "Installing Azure CLI extension for Static Web Apps..."
        az extension add --name staticwebapp --only-show-errors || echo "Extension already installed"

    # Disconnect the Static Web App from GitHub if needed
    - name: Disconnect Static Web App from GitHub
      shell: bash
      run: |
        echo "Disconnecting Static Web App from GitHub source control..."
        az staticwebapp disconnect \
          --name ${{ inputs.app-name }} \
          --resource-group ${{ inputs.resource-group }} \
          --no-wait || echo "Failed to disconnect or already disconnected"

    # Setup Node.js for SWA CLI
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # Install SWA CLI
    - name: Install Azure Static Web Apps CLI
      shell: bash
      run: |
        echo "Installing SWA CLI..."
        npm install --no-fund --no-audit --loglevel=error -g @azure/static-web-apps-cli

    # Deploy using the direct deployment token approach
    - name: Deploy Site via SWA CLI Direct Token Method
      shell: bash
      run: |
        echo "Deploying to ${{ inputs.env }} using SWA CLI direct token method..."
        # Add sleep to ensure file system is ready and disconnection completes
        sleep 5
        # Use chmod to ensure executable permissions
        chmod -R 755 ${{ inputs.artifact-path }}
        
        # Set SWA_CLI_DEPLOYMENT_TOKEN environment variable explicitly
        export SWA_CLI_DEPLOYMENT_TOKEN="${{ inputs.deployment_token }}"
        
        # Deploy using direct token approach (doesn't require app-name or resource-group)
        swa deploy "${{ inputs.artifact-path }}" \
          --deployment-token "${{ inputs.deployment_token }}" \
          --verbose
      
    # Get the deployment URL for output
    - name: Get Deployment URL
      id: get_deployment_url
      shell: bash
      run: |
        # Get the URL from Azure CLI
        URL=$(az staticwebapp show --name ${{ inputs.app-name }} --resource-group ${{ inputs.resource-group }} --query "defaultHostname" -o tsv)
        if [[ -n "$URL" ]]; then
          FULL_URL="https://$URL"
          echo "url=$FULL_URL" >> $GITHUB_OUTPUT
          echo "Deployment URL: $FULL_URL"
        else
          echo "url=https://${{ inputs.app-name }}.azurestaticapps.net" >> $GITHUB_OUTPUT
          echo "Could not retrieve URL, using default format"
        fi
