name: "SWA Deploy"
description: "Deploy site via SWA CLI with Azure CLI fallback from a downloaded artifact."
inputs:
  artifact-name:
    description: "The name of the artifact to download"
    required: true
  app-name:
    description: "The SWA app name"
    required: true
  resource-group:
    description: "The resource group for the SWA app"
    required: true
  env:
    description: "The deployment environment (e.g. staging, prod)"
    required: true
  artifact-path:
    description: "Local path to download the artifact to"
    required: false
    default: "./build-artifact"
  azure_credentials:
    description: "Azure credentials for authentication"
    required: true
  deployment_token:
    description: "SWA deployment token"
    required: true
outputs:
  deployment_url:
    description: "The URL of the deployed application"
    value: ${{ steps.get_deployment_url.outputs.url }}
runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Download Web App Artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ inputs.artifact-path }}

    # Login to Azure
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ inputs.azure_credentials }}

    # Install Azure CLI extension for Static Web Apps
    - name: Install Azure CLI extensions
      shell: bash
      run: |
        echo "Installing Azure CLI extension for Static Web Apps..."
        az extension add --name staticwebapp --only-show-errors || echo "Extension already installed"

    # Setup Node.js for SWA CLI
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # Install SWA CLI
    - name: Install Azure Static Web Apps CLI
      shell: bash
      run: |
        echo "Installing SWA CLI..."
        npm install --no-fund --no-audit --loglevel=error -g @azure/static-web-apps-cli

    # Ensure the config file is properly placed
    - name: Prepare configuration
      shell: bash
      run: |
        echo "Preparing configuration..."
        # Ensure the config directory exists in the artifact
        mkdir -p ${{ inputs.artifact-path }}/.config
        
        # Copy the config file if it doesn't exist in the artifact
        if [ ! -f "${{ inputs.artifact-path }}/.config/staticwebapp.config.json" ]; then
          echo "Copying staticwebapp.config.json to artifact directory..."
          cp .config/staticwebapp.config.json ${{ inputs.artifact-path }}/.config/
        else
          echo "Config file already exists in artifact directory"
        fi
        
        # Display the config for verification
        echo "Using configuration:"
        cat ${{ inputs.artifact-path }}/.config/staticwebapp.config.json

    # Deploy using the official Azure Static Web Apps GitHub Action
    - name: Deploy to Azure Static Web Apps
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ inputs.deployment_token }}
        repo_token: "dummy-token" # Not actually used for deployment
        action: "upload"
        app_location: ${{ inputs.artifact-path }}
        api_location: ""
        output_location: ""
        config_location: ".config"
        skip_app_build: true
      
    # Get the deployment URL for output
    - name: Get Deployment URL
      id: get_deployment_url
      shell: bash
      run: |
        # Get the URL from Azure CLI
        URL=$(az staticwebapp show --name ${{ inputs.app-name }} --resource-group ${{ inputs.resource-group }} --query "defaultHostname" -o tsv)
        if [[ -n "$URL" ]]; then
          FULL_URL="https://$URL"
          echo "url=$FULL_URL" >> $GITHUB_OUTPUT
          echo "Deployment URL: $FULL_URL"
        else
          echo "url=https://${{ inputs.app-name }}.azurestaticapps.net" >> $GITHUB_OUTPUT
          echo "Could not retrieve URL, using default format"
        fi
