name: "SWA Deploy"
description: "Deploy site via SWA CLI with Azure CLI fallback from a downloaded artifact."
inputs:
  artifact-name:
    description: "The name of the artifact to download"
    required: true
  app-name:
    description: "The SWA app name"
    required: true
  resource-group:
    description: "The resource group for the SWA app"
    required: true
  env:
    description: "The deployment environment (e.g. staging, prod)"
    required: true
  artifact-path:
    description: "Local path to download the artifact to"
    required: false
    default: "./build-artifact"
  azure_credentials:
    description: "Azure credentials for authentication"
    required: true
  deployment_token:
    description: "SWA deployment token"
    required: true
outputs:
  deployment_url:
    description: "The URL of the deployed application"
    value: ${{ steps.get_deployment_url.outputs.url }}
runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Download Web App Artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ inputs.artifact-path }}

    # Login to Azure first - this will prevent the interactive login prompt
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ inputs.azure_credentials }}

    # Note: Direct deployment via Azure CLI is not supported
    # This step is included for clarity but will be skipped in favor of SWA CLI
    - name: Check Azure CLI capabilities
      id: az_cli_check
      shell: bash
      run: |
        echo "Installing Azure CLI extension for Static Web Apps..."
        az extension add --name staticwebapp --only-show-errors || echo "Extension already installed"
        
        echo "Checking Static Web App status..."
        az staticwebapp show \
          --name ${{ inputs.app-name }} \
          --resource-group ${{ inputs.resource-group }} \
          --query "defaultHostname" -o tsv || echo "az_cli_failed=true" >> $GITHUB_OUTPUT
        
        # Direct deployment via CLI isn't supported, marking for SWA CLI fallback
        echo "az_cli_failed=true" >> $GITHUB_OUTPUT
      continue-on-error: true

    # Use SWA CLI for deployment (recommended method)
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Azure Static Web Apps CLI
      shell: bash
      run: |
        echo "Installing SWA CLI..."
        npm install --no-fund --no-audit --loglevel=error -g @azure/static-web-apps-cli

    - name: Deploy Site via SWA CLI
      shell: bash
      run: |
        echo "Deploying to ${{ inputs.env }} using SWA CLI from artifact..."
        # Add sleep to ensure file system is ready
        sleep 2
        # Use chmod to ensure executable permissions
        chmod -R 755 ${{ inputs.artifact-path }}
        
        # Set SWA_CLI_DEPLOYMENT_TOKEN environment variable explicitly
        export SWA_CLI_DEPLOYMENT_TOKEN="${{ inputs.deployment_token }}"
        
        # Deploy using SWA CLI
        swa deploy "${{ inputs.artifact-path }}" \
          --deployment-token "${{ inputs.deployment_token }}" \
          --env "${{ inputs.env }}" \
          --app-name "${{ inputs.app-name }}" \
          --resource-group "${{ inputs.resource-group }}" \
          --no-use-keychain \
          --verbose
    
    # Get the deployment URL for output
    - name: Get Deployment URL
      id: get_deployment_url
      shell: bash
      run: |
        # Get the URL from Azure CLI
        URL=$(az staticwebapp show --name ${{ inputs.app-name }} --resource-group ${{ inputs.resource-group }} --query "defaultHostname" -o tsv)
        if [[ -n "$URL" ]]; then
          FULL_URL="https://$URL"
          echo "url=$FULL_URL" >> $GITHUB_OUTPUT
          echo "Deployment URL: $FULL_URL"
        else
          echo "url=https://${{ inputs.app-name }}.azurestaticapps.net" >> $GITHUB_OUTPUT
          echo "Could not retrieve URL, using default format"
        fi
