name: "SWA Deploy"
description: "Deploy site via SWA CLI with Azure CLI fallback from a downloaded artifact."
inputs:
  artifact-name:
    description: "The name of the artifact to download"
    required: true
  app-name:
    description: "The SWA app name"
    required: true
  resource-group:
    description: "The resource group for the SWA app"
    required: true
  env:
    description: "The deployment environment (e.g. staging, prod)"
    required: true
  artifact-path:
    description: "Local path to download the artifact to"
    required: false
    default: "./build-artifact"
runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Download Web App Artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ inputs.artifact-path }}
        
    - name: Fix staticwebapp.config.json
      shell: bash
      run: |
        CONFIG_PATH="${{ inputs.artifact-path }}/.config/staticwebapp.config.json"
        
        if [ -f "$CONFIG_PATH" ]; then
          echo "Updating $CONFIG_PATH to use 'rewrite' instead of 'serve'..."
          sed -i 's/"serve":/"rewrite":/g' "$CONFIG_PATH"
          sed -i 's/,"statusCode": 200//g' "$CONFIG_PATH"
          echo "Configuration updated successfully."
          cat "$CONFIG_PATH"
          
          # Copy to root if it doesn't exist there (as a fallback)
          ROOT_CONFIG="${{ inputs.artifact-path }}/staticwebapp.config.json"
          if [ ! -f "$ROOT_CONFIG" ]; then
            echo "Copying config to root location as well..."
            cp "$CONFIG_PATH" "$ROOT_CONFIG"
          fi
        else
          echo "Warning: Config file not found at $CONFIG_PATH"
        fi

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Azure Static Web Apps CLI
      shell: bash
      run: |
        echo "Installing SWA CLI..."
        npm install --no-fund --no-audit --loglevel=error -g @azure/static-web-apps-cli

    # Try SWA CLI first as the primary method
    - name: Deploy Site via SWA CLI (Primary Method)
      id: swa_cli_deploy
      shell: bash
      run: |
        echo "Deploying to ${{ inputs.env }} using SWA CLI from artifact..."
        swa deploy ${{ inputs.artifact-path }} \
          --deployment-token ${{ env.AZURE_STATIC_WEB_APPS_API_TOKEN }} \
          --env ${{ inputs.env }} || echo "::set-output name=swa_cli_failed::true"
      env:
        AZURE_STATIC_WEB_APPS_API_TOKEN: ${{ env.AZURE_STATIC_WEB_APPS_API_TOKEN }}
      continue-on-error: true

    # Only try Azure CLI if SWA CLI fails
    - name: Install Azure CLI (Fallback)
      if: steps.swa_cli_deploy.outputs.swa_cli_failed == 'true'
      shell: bash
      run: |
        echo "SWA CLI deployment failed, installing Azure CLI as fallback..."
        curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
      continue-on-error: true
        
    - name: Deploy using Azure CLI (Fallback Method)
      if: steps.swa_cli_deploy.outputs.swa_cli_failed == 'true'
      shell: bash
      run: |
        echo "Installing Azure CLI extension for Static Web Apps..."
        az extension add --name staticwebapps --only-show-errors || echo "Extension installation failed, continuing..."
        
        echo "Deploying to ${{ inputs.env }} environment using Azure CLI..."
        az staticwebapp deployment create \
          --name ${{ inputs.app-name }} \
          --resource-group ${{ inputs.resource-group }} \
          --source ${{ inputs.artifact-path }} \
          --environment ${{ inputs.env }} \
          --token ${{ env.AZURE_STATIC_WEB_APPS_API_TOKEN }} \
          --verbose
      env:
        AZURE_STATIC_WEB_APPS_API_TOKEN: ${{ env.AZURE_STATIC_WEB_APPS_API_TOKEN }}
