name: "SWA Deploy"
description: "Deploy site via SWA CLI with Azure CLI fallback from a downloaded artifact."
inputs:
  artifact-name:
    description: "The name of the artifact to download"
    required: true
  run-id:
    description: "The run ID from which to download the artifact"
    required: true
  app-name:
    description: "The SWA app name"
    required: true
  resource-group:
    description: "The resource group for the SWA app"
    required: true
  env:
    description: "The deployment environment (e.g. staging, prod)"
    required: true
  artifact-path:
    description: "Local path to download the artifact to"
    required: false
    default: "./build-artifact"
  azure_credentials:
    description: "Azure credentials for authentication"
    required: true
  deployment_token:
    description: "SWA deployment token"
    required: true
outputs:
  deployment_url:
    description: "The URL of the deployed application"
    value: ${{ steps.get_deployment_url.outputs.url }}
  deployment_id:
    description: "Unique identifier for this deployment"
    value: ${{ steps.generate_deployment_id.outputs.id }}
runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Download Web App Artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        run-id: ${{ inputs.run-id }}
        path: ${{ inputs.artifact-path }}

    # Login to Azure
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ inputs.azure_credentials }}

    # Ensure Azure CLI Logic Extension is Installed
    - name: Ensure Azure CLI Logic Extension is Installed
      shell: bash
      run: |
        if ! az extension show --name logic &>/dev/null; then
          az extension add --name logic --yes
        else
          echo "Azure CLI logic extension is already installed."
        fi

    # Ensure the config file is properly placed
    - name: Prepare configuration
      shell: bash
      run: |
        echo "Preparing configuration..."
        mkdir -p ${{ inputs.artifact-path }}/.config
        if [ ! -f "${{ inputs.artifact-path }}/.config/staticwebapp.config.json" ]; then
          echo "Copying staticwebapp.config.json to artifact directory..."
          cp .config/staticwebapp.config.json ${{ inputs.artifact-path }}/.config/
        else
          echo "Config file already exists in artifact directory"
        fi
        echo "Using configuration:"
        cat ${{ inputs.artifact-path }}/.config/staticwebapp.config.json

    - name: Get SWA Deployment Token
      id: get_token
      shell: bash
      run: |
        TOKEN=$(az staticwebapp secrets list --name ${{ inputs.app-name }} --resource-group ${{ inputs.resource-group }} --query "properties.apiKey" -o tsv)
        echo "::add-mask::$TOKEN"
        echo "deployment_token=$TOKEN" >> $GITHUB_OUTPUT

    - name: Get Deployment Information
      id: get_deployment_info
      shell: bash
      run: |
        echo "deployment_id=${{ github.event.inputs.deploymentId }}" >> $GITHUB_OUTPUT
        echo "artifact_id=${{ github.event.inputs.artifactId }}" >> $GITHUB_OUTPUT
        echo "run_id=${{ github.event.inputs.runID }}" >> $GITHUB_OUTPUT
        echo "commit_sha=${{ github.sha }}" >> $GITHUB_OUTPUT
        echo "timestamp=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT

    - name: Deploy to Azure Static Web Apps
      id: deploy
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ steps.get_token.outputs.deployment_token }}
        repo_token: ${{ github.token }}
        action: "upload"
        app_location: ${{ inputs.artifact-path }}
        api_location: ""
        output_location: ""
        config_file_location: ".config"
        skip_app_build: true
      env:
        DEPLOYMENT_PROVIDER: "DevOps"
        DEPLOYMENT_ID: ${{ steps.generate_deployment_id.outputs.id }}

    - name: Get Deployment URL
      id: get_deployment_url
      shell: bash
      run: |
        URL=$(az staticwebapp show --name ${{ inputs.app-name }} --resource-group ${{ inputs.resource-group }} --query "defaultHostname" -o tsv)
        if [[ -n "$URL" ]]; then
          FULL_URL="https://$URL"
          echo "url=$FULL_URL" >> $GITHUB_OUTPUT
          echo "Deployment URL: $FULL_URL"
        else
          echo "url=https://${{ inputs.app-name }}.azurestaticapps.net" >> $GITHUB_OUTPUT
          echo "Could not retrieve URL, using default format"
        fi
