export const contactFormStyles = {
  form: "space-y-6",
  inputGrid: "grid grid-cols-1 md:grid-cols-2 gap-6",
  input: [
    "w-full",
    "px-4 py-3",
    "rounded-lg",
    "bg-[hsl(var(--card))]",
    "border",
    "border-[hsl(var(--border))]",
    "focus:border-[hsl(var(--primary))] focus:outline-none",
    "transition-colors duration-200",
  ].join(" "),
  textarea: [
    "w-full",
    "px-4 py-3",
    "rounded-lg",
    "bg-[hsl(var(--card))]",
    "border",
    "border-[hsl(var(--border))]",
    "focus:border-[hsl(var(--primary))] focus:outline-none",
    "transition-colors duration-200",
    "resize-none",
  ].join(" "),
  button: [
    "w-full",
    "px-8 py-3",
    "bg-[hsl(var(--color-primary))]",
    "hover:bg-[hsl(var(--color-hover, var(--color-primary)))]",
    "rounded-lg",
    "font-medium",
    "transition-colors duration-200",
    "disabled:opacity-50 disabled:cursor-not-allowed",
  ].join(" "),
  error: "text-[hsl(var(--destructive))] text-sm mt-1",
} as const;
